version: '3'

services:
    cypress:
      build:
        context: .
        dockerfile: cypressTest.Dockerfile
      container_name: e2e
      environment:
        - CYPRESS_baseUrl=http://localhost
      working_dir: /e2e
      command: "--browser chrome" 
      volumes:
        - ./cypress:/e2e/cypress
        - ./cypress.json:/e2e/cypress.json
      network_mode: "host"